### ISSUE TITLE
Do not generate routes, tests and plugin by default

### ISSUE THREAD

**Issue by mcollina** [platformatic/rabbitmq-hooks#42]
As titled

**Comment by marcopiraccini** [comment]
@mcollina  I think this is on `meraki`. We set the generator options here: https://github.com/platformatic/meraki/blob/main/src/main/generate.mjs#L142 
So this overrides every "default config" and set always `tests`/`plugin` to `true`.
This stackable do not changes the defaults for the base generator, which is to set both to `false`: https://github.com/platformatic/platformatic/blob/main/packages/generators/lib/base-generator.js#L53

Going to do a PR on meraki for this. 
cc'ing also @leorossi

**Comment by marcopiraccini** [comment]
Added the issue in meraki: https://github.com/platformatic/meraki/issues/706
